[package]
name = "rustix"
version = "0.1.0"
authors = ["James Jenkins <applesmacs@yahoo.com>"]

[dependencies]
reqwest = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
maplit = "0.1.4"
regex = "0.2"
chrono = "0.4.0"

diesel = { version = "0.16.0", features = ["postgres"] }
diesel_codegen = { version = "0.16.0", features = ["postgres"] }
dotenv = "0.9.0"

rand = "0.4"
